language: c
sudo: required
dist: trusty
before_install:
    - sudo add-apt-repository -y ppa:gluster/glusterfs-4.1
    - sudo apt-get update -qq
    - sudo apt-get install -qq glusterfs targetcli uuid-dev
# Need tcmu-runner here

script:
- ./autogen.sh
- ./configure
- make

git:
  depth: 3

